### PR TITLE
Create ru-ru.json

### PR DESCRIPTION
**Pull request by r-liner**
**PR changes**

Added russian language to bot`s languages
Full translation on russian language

### CODE REVIEW

**Comment by eibex** [comment]
Thanks for the PR! It looks good, only needs a few changes before we merge as some strings aren't compatible with Discord's API:

`brief-settings-notify` is 118 characters, it must be 100 or less

`brief-settings-systemchannel` is 105 characters, it must be 100 or less

**Comment by r-liner** [comment]
> Thanks for the PR! It looks good, only needs a few changes before we merge as some strings aren't compatible with Discord's API:
> 
> `brief-settings-notify` is 118 characters, it must be 100 or less
> 
> `brief-settings-systemchannel` is 105 characters, it must be 100 or less

It`s fixed for now

**Comment by eibex** [comment]
Hey @r-liner before I publish a new release, I just wanted to ask if it would be correct to replace line 2's "Russian" with "Русский"?

**Comment by r-liner** [comment]
As you wish

**Pull request merged**
