### PR TITLE
Translation update, slash commands errors handler added

### PR DESCRIPTION
**Pull request by r-liner**
**PR changes**
- Updated translation `ru-ru.json`
- Added slash commands errors handler `cogs/errors.py`

### CODE REVIEW

**Comment by eibex** [comment]
Hi, thanks for the PR! I left a comment before we can merge :) Would you mind making that change?

**Comment by r-liner** [comment]
I don't got the question

**Comment by eibex** [comment]
I pushed a commit in the PR branch. It should work as intended now.

Thanks for spotting the issue on command errors not being captured.

**Review by eibex — APPROVED** [review]

**Comment by r-liner** [comment]
You're welcome. Glad to help.

**Pull request merged**
