### PR TITLE
Re-work message clean up, re-work of the admin system and cleaning up left guilds

### LINKED ISSUE #52: DB not self-cleaning after deleting servers
**Describe the bug**

The DB does not clean admin roles, message IDs and related reactions/roles if a server does not exist anymore.

**To Reproduce**

1. Create a server
2. Add an admin
3. Add a reaction-role message
4. Delete the server
5. Restart the bot or wait 24 hours

**Expected behavior**
The DB cleans itself

### PR DESCRIPTION
**Pull request by Edwinexd**
Fixes #52 by deleting a guilds database entries after leaving the guild / if the guild gets deleted.
In order to do this I added another database function (remove_guild) which just removes everything directly connected to the guild (message, reactionroles, systemchannels). **Please note**: This will NOT remove the admin role id from the database as admins table does not refer to which guild the admin role belongs to.

### CODE REVIEW

**Comment by eibex** [comment]
Thanks a lot for this PR! I will test it later this evening but it looks good. 

My bad for forgetting to attach guild IDs to admin IDs. 

I have only a single question: would this work if the bot and/or discord api was down when the guild gets deleted?

**Comment by Edwinexd** [comment]
No it would not work as it is done right now, it could be down by fetching every guild that the bot has database entries in every now and then but that will be a lot of API calls and it would probably be wise to in that case store the guilds "to be removed" for 24 hrs then re-check to deal with any potential invalid responses from Discords API. Hope that makes any sense, I'd be able to help do that if it sounds good 👍

**Comment by eibex** [comment]
That was what I tried to achieve in the current master on lines 266-297, but it is not working as intended. 

The similar code for deleted messages (lines 222-256) seems to be working correctly when the message is deleted but the guild is not.

My current guess is that if the guild is deleted the except and/or if functions are not triggered properly. I haven't had the time to debug it sadly.

**Comment by eibex** [comment]
It would be great if we could go the 24h route so that the change is retroactive and does not assume 100% uptime.

**Comment by Edwinexd** [comment]
👍 I took a quick look at 266-297 and I think the reason it is currently not working is because: `db.fetch_all_guilds()` only checks for guilds that have set up a "system channel". Although it is probably wise to redo-it with the "24h system". I'll try to get to work on it tomorrow. On another note we should prob redo the admin roles system to save the guild it belongs aswell as its probably good to get that sorted now so when the redone cleaning is done it wont need another redo to patch the role ids.

**Comment by eibex** [comment]
Thanks for spotting it so quickly. I agree with re-working the admin system as well. I hope I can get a good look at it this weekend. 

Thanks for taking interest in this project 😃

**Comment by Edwinexd** [comment]
Glad I can help! :) 
I redid the admin database structure and added the table needed to use the "24h system" so far, will get to editing bot.py & adding database functions to interact with the new tables

**Comment by eibex** [comment]
Thanks for the quick changes!

This weekend I will add the necessary updates for database migration. I think the most painless way to do this is to outright delete the old admins table, recreate it with the new column and let users re-run the command to add admins.

Once I did that and tested everything I will merge and release 2.1.0

**Comment by Edwinexd** [comment]
ye that is probably the best way to do it, otherwise it would be a lot of brute-forcing to figure out what role belongs to what guild, btw if you could add me on Discord that could probably ease some communication **Edwin#3726**. I'll probably push some commits tommorow to add the same 24h system for RL messages, proper management of admin roles and a way to actually verify if the user is an admin (currently just calling functions "wrongly")

**Comment by eibex** [comment]
The reason I don’t check for the actual Administrator permission (only done for adding and removing admins) is to have other users manage the bot by giving them a certain role without giving them full control over the server.

(Unless this isn’t what you meant with checking for actual admins)

The code could be (or most likely it is) inefficient as I am not a developer and this is just a hobby of mine.

**Comment by Edwinexd** [comment]
Oh my bad! I ment the isadmin() function which checks if the user has the admin role, my bad for being unclear!

**Comment by Edwinexd** [comment]
Hey! I just noticed that anyone with an admin role can kill, restart or update the bot, that can be abused if its added to multiple servers and in one of them decides to mess with it they can without any problem, I suggest to add this decor to the management commands https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=is_owner#discord.ext.commands.is_owner to only make those commands usable by the bot owner

**Review by Edwinexd — COMMENTED** [review]
* Clean up admin roles that cant be migrated not guilds

**Comment by eibex** [comment]
I agree with the `is_owner` decorator for those three commands as I do not even see a reason for which other administrators need to have access to them.

I see that you already made the code to `ALTER` the admins table. What's left to do now? I can complete the remaining tasks tomorrow if you want, you already did a ton of work (thanks!).

**Comment by Edwinexd** [comment]
I don't think there is anything more to do than to write a little changelog. No worries! 🙂

**Comment by eibex** [comment]
Thanks again for taking the time to make such a big PR!

**Pull request merged**
